[package]
name = "fuck_dance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder="1.4"
glam = "0.23"
half = "2.2.1"
bitflags = "1.3"
bytemuck = "1.13"